export const ecamDData = {
  m0: [
    [
      { span: 2, props: { text: '附件名称' } },
      { span: 2.8, type: 'input', field: 'Attachment_Name', props: { text: '', readOnly: true } },
      { span: 1.4, props: { text: '', color: '#D9D9D9' } },
      { span: 2.8, props: { text: '' } },
    ],
    [
      { span: 2, props: { text: '产品名称', aiLabelType: 1, aiTextFor: 'PWB_Model_name_ai' } },
      { span: 2.8, type: 'input', field: 'PWB_Model_name_ai', props: { text: '' } },
      { span: 1.4, props: { text: '', color: '#D9D9D9' } },
      { span: 2.8, props: { text: '' } },
    ],
    [
      { span: 2, props: { text: '产品用途', aiLabelType: 1, aiTextFor: 'product_usage_ai' } },
      {
        span: 2.8,
        type: 'select',
        field: 'product_usage_ai',
        props: {
          edit: true,
          text: '',
          optionList: [
            { label: '消费电子', value: 1 },
            { label: '汽车产品', value: 2 },
            { label: '军工', value: 3 },
            { label: '医疗', value: 4 },
            { label: '通信', value: 5 },
            { label: '航天', value: 6 },
          ],
        },
      },
      { span: 1.4, props: { text: '', color: '#D9D9D9' } },
      { span: 2.8, props: { text: '' } },
    ],
    [
      { span: 2, props: { text: '客户代码' } },
      { span: 2.8, type: 'input', field: 'Customer_code', props: { text: '' } },
      { span: 1.4, props: { text: '', color: '#D9D9D9' } },
      { span: 2.8, props: { text: '' } },
    ],
    [
      { span: 2, props: { text: '客户名称', aiLabelType: 1, aiTextFor: 'Customer_brand_ai' } },
      { span: 2.8, type: 'input', field: 'Customer_brand_ai', props: { text: '' } },
      { span: 1.4, props: { text: '', color: '#D9D9D9' } },
      { span: 2.8, props: { text: '' } },
    ],
    [
      { span: 2, props: { text: '订单数量' } },
      {
        span: 2.8,
        type: 'input',
        field: 'Order_Quantity',
        props: { text: '', dataType: 'number', validatorFlag: 'regexPatternWithZero', funcName: 'calcOrderArea' },
      },
      {
        span: 1.4,
        type: 'select',
        props: {
          text: '/PCS',
          optionList: [
            { label: '/PCS', value: 1 },
            { label: '/SET', value: 2 },
          ],
        },
      },
      { span: 2.8, type: 'text', field: 'Order_Quantity_ai', props: { text: '', color: '#a5a3a3', textColor: '#fff' } },
    ],
    [
      { span: 2, props: { text: '订单面积' } },
      { span: 2.8, type: 'input', field: 'Order_area', props: { text: '', dataType: 'number', validatorFlag: 'doubleValidator0' } },
      { span: 1.4, props: { text: 'm2', color: '#D9D9D9' } },
      { span: 2.8, props: { text: '' } },
    ],
    [
      { span: 2, props: { text: 'IPC标准', aiLabelType: 1, aiTextFor: 'IPC_standard_ai' } },
      {
        span: 2.8,
        type: 'select',
        field: 'IPC_standard_ai',
        props: {
          edit: true,
          text: '',
          optionList: [
            { label: '汽车板', value: 1 },
            { label: '军品板', value: 2 },
            { label: 'IPC Class 3', value: 3 },
            { label: 'IPC Class 2', value: 4 },
          ],
        },
      },
      { span: 1.4, props: { text: '', color: '#D9D9D9' } },
      { span: 2.8, props: { text: '' } },
    ],
    [
      { span: 2, props: { text: '打叉板标准', aiLabelType: 1, aiTextFor: 'X-OUT_standard_ai' } },
      {
        span: 2.8,
        type: 'select',
        field: 'X-OUT_standard_ai',
        props: {
          edit: true,
          text: '',
          optionList: [
            { label: '不允许叉板', value: 1 },
            { label: '允许叉板', value: 2 },
          ],
          funcName: 'refreshPane',
        },
      },
      { span: 1.4, props: { text: '', color: '#D9D9D9' } },
      { span: 2.8, props: { text: '' } },
    ],
    [
      { span: 2, props: { text: '打叉数量', color: '#D9E1F4', aiLabelType: 1, aiTextFor: 'X-OUT_quantity_ai', visible: false } },
      {
        span: 2.8,
        type: 'input',
        field: 'X-OUT_quantity_ai',
        props: { text: '', dataType: 'number', validatorFlag: 'regexPatternWithZero', visible: false },
      },
      { span: 1.4, props: { text: '', color: '#D9D9D9', visible: false } },
      { span: 2.8, props: { text: '', visible: false } },
    ],
    [
      { span: 2, props: { text: '环保要求', aiLabelType: 1, aiTextFor: 'environ_standard_ai' } },
      {
        span: 2.8,
        type: 'select',
        field: 'environ_standard_ai',
        props: {
          edit: true,
          text: '',
          optionList: [
            { label: 'SONY', value: 1 },
            { label: 'POHS', value: 2 },
            { label: 'REACH', value: 3 },
            { label: 'ROHS', value: 4 },
            { label: '无卤(HF)', value: 5 },
          ],
        },
      },
      { span: 1.4, props: { text: '', color: '#D9D9D9' } },
      { span: 2.8, props: { text: '' } },
    ],
    [
      { span: 2, props: { text: '包装要求', aiLabelType: 1, aiTextFor: 'Packaging_ai' } },
      {
        span: 2.8,
        type: 'select',
        field: 'Packaging_ai',
        props: {
          edit: true,
          text: '',
          optionList: [
            { label: '真空包装', value: 1 },
            { label: '防静电包装', value: 2 },
          ],
        },
      },
      { span: 1.4, props: { text: '', color: '#D9D9D9' } },
      { span: 2.8, props: { text: '' } },
    ],
    [
      { span: 2, props: { text: '板翘曲(max)', aiLabelType: 1, aiTextFor: 'bow_twist_ai' } },
      { span: 2.8, type: 'input', field: 'bow_twist_ai', props: { text: '' } },
      { span: 1.4, props: { text: '', color: '#D9D9D9' } },
      { span: 2.8, props: { text: '' } },
    ],
    [
      { span: 2, props: { text: '可返工修补', aiLabelType: 1, aiTextFor: 'wire_repair_ai' } },
      {
        span: 2.8,
        type: 'select',
        field: 'wire_repair_ai',
        props: {
          edit: true,
          text: '',
          optionList: [
            { label: '是', value: 1 },
            { label: '否', value: 2 },
          ],
        },
      },
      { span: 1.4, props: { text: '', color: '#D9D9D9' } },
      { span: 2.8, props: { text: '' } },
    ],
    [
      { span: 2, props: { text: '离子污染', aiLabelType: 1, aiTextFor: 'Ionic_contamin_ai' } },
      { span: 2.8, type: 'input', field: 'Ionic_contamin_ai', props: { text: '' } },
      { span: 1.4, props: { text: 'ug/m2', color: '#D9D9D9' } },
      { span: 2.8, props: { text: '' } },
    ],
    [
      { span: 2, props: { text: '二维码要求', aiLabelType: 1, aiTextFor: 'Quick_Response_code_ai' } },
      {
        span: 2.8,
        type: 'select',
        field: 'Quick_Response_code_ai',
        props: {
          edit: true,
          text: '',
          optionList: [
            { label: '是', value: 1 },
            { label: '否', value: 2 },
          ],
        },
      },
      { span: 1.4, props: { text: '', color: '#D9D9D9' } },
      { span: 2.8, props: { text: '' } },
    ],
    [
      { span: 2, props: { text: '难度等级', aiLabelType: 1, aiTextFor: 'Difficulty_level_ai' } },
      {
        span: 2.8,
        type: 'select',
        field: 'Difficulty_level_ai',
        props: {
          edit: true,
          text: '',
          optionList: [
            { label: '低等', value: 1 },
            { label: '中等', value: 2 },
            { label: '高等', value: 3 },
          ],
        },
      },
      { span: 1.4, props: { text: '', color: '#D9D9D9' } },
      { span: 2.8, props: { text: '' } },
    ],
  ],
}

const colsCount = 12
export const ecamDHeader = [
  [
    {
      span: colsCount,
      type: 'button',
      shown: true,
      props: { colorType: 'primary', text: '-    订单信息', funcName: 'collapsePaneButton1', wAdjust: 0, hAdjust: 0 },
    },
  ],
  [
    {
      span: colsCount,
      type: 'button',
      shown: true,
      props: { colorType: 'primary', text: '-    基本信息', funcName: 'collapsePaneButton2', wAdjust: 0, hAdjust: 0 },
    },
  ],
  [
    {
      span: colsCount,
      type: 'button',
      shown: false,
      props: { colorType: 'primary', text: '+    板料信息', funcName: 'collapsePaneButton3', wAdjust: 0, hAdjust: 0 },
    },
  ],
  [
    {
      span: colsCount,
      type: 'button',
      shown: false,
      props: { colorType: 'primary', text: '+    开料信息', funcName: 'collapsePaneButton4', wAdjust: 0, hAdjust: 0 },
    },
  ],
  [
    {
      span: colsCount,
      type: 'button',
      shown: false,
      props: { colorType: 'primary', text: '+    内 + 压信息', funcName: 'collapsePaneButton15', wAdjust: 0, hAdjust: 0 },
    },
  ],
  [
    {
      span: colsCount,
      type: 'button',
      shown: false,
      props: { colorType: 'primary', text: '+    钻孔信息', funcName: 'collapsePaneButton5', wAdjust: 0, hAdjust: 0 },
    },
  ],
  [
    {
      span: colsCount,
      type: 'button',
      shown: false,
      props: { colorType: 'primary', text: '+    镭射信息', funcName: 'collapsePaneButton16', wAdjust: 0, hAdjust: 0 },
    },
  ],
  [
    {
      span: colsCount,
      type: 'button',
      shown: false,
      props: { colorType: 'primary', text: '+    特殊钻孔信息', funcName: 'collapsePaneButton17', wAdjust: 0, hAdjust: 0 },
    },
  ],
  [
    {
      span: colsCount,
      type: 'button',
      shown: false,
      props: { colorType: 'primary', text: '+    阻焊信息', funcName: 'collapsePaneButton6', wAdjust: 0, hAdjust: 0 },
    },
  ],
  [
    {
      span: colsCount,
      type: 'button',
      shown: false,
      props: { colorType: 'primary', text: '+    字符信息', funcName: 'collapsePaneButton7', wAdjust: 0, hAdjust: 0 },
    },
  ],
  [
    {
      span: colsCount,
      type: 'button',
      shown: false,
      props: { colorType: 'primary', text: '+    表面处理信息', funcName: 'collapsePaneButton8', wAdjust: 0, hAdjust: 0 },
    },
  ],
  [
    {
      span: colsCount,
      type: 'button',
      shown: false,
      props: { colorType: 'primary', text: '+    金手指&电硬金信息', funcName: 'collapsePaneButton9', wAdjust: 0, hAdjust: 0 },
    },
  ],
  [
    {
      span: colsCount,
      type: 'button',
      shown: false,
      props: { colorType: 'primary', text: '+    成型信息', funcName: 'collapsePaneButton10', wAdjust: 0, hAdjust: 0 },
    },
  ],
  [
    {
      span: colsCount,
      type: 'button',
      shown: false,
      props: { colorType: 'primary', text: '+    电测信息', funcName: 'collapsePaneButton11', wAdjust: 0, hAdjust: 0 },
    },
  ],
  [
    {
      span: colsCount,
      type: 'button',
      shown: false,
      props: { colorType: 'primary', text: '+    特殊工艺信息', funcName: 'collapsePaneButton12', wAdjust: 0, hAdjust: 0 },
    },
  ],
  [
    {
      span: colsCount,
      type: 'button',
      shown: false,
      props: { colorType: 'primary', text: '+    内层线路信息', funcName: 'collapsePaneButton13', wAdjust: 0, hAdjust: 0 },
    },
  ],
  [
    {
      span: colsCount,
      type: 'button',
      shown: false,
      props: { colorType: 'primary', text: '+    外层线路信息', funcName: 'collapsePaneButton14', wAdjust: 0, hAdjust: 0 },
    },
  ],
]

export const ecamResultData = {
  headerTextArray: ['项目名称', '参数值', '单位'],
  titleList: [
    { title: '订单信息' },
    { title: '基本信息' },
    { title: '板料信息' },
    { title: '开料信息' },
    { title: '内压信息' },
    { title: '钻孔信息' },
    { title: '镭射信息' },
    { title: '特殊钻孔信息' },
    { title: '阻焊信息' },
    { title: '字符信息' },
    { title: '表面处理信息' },
    { title: '金手指&电硬金信息' },
    { title: '成型信息' },
    { title: '电测信息' },
    { title: '特殊工艺信息' },
    { title: '内层线路信息' },
    { title: '外层线路信息' },
    { title: '扩展参数' },
  ],
  projectList: {
    m0: [
      { label: '附件名称', valueArr: ['demo333.rar'], unitArr: [''] },
      { label: '产品名称', valueArr: ['???'], unitArr: [''] },
      { label: '产品用途', valueArr: [''], unitArr: [''] },
      { label: '客户代码', valueArr: [''], unitArr: [''] },
      { label: '客户名称', valueArr: ['DELTA'], unitArr: [''] },
      { label: '订单数量', valueArr: [''], unitArr: ['/PCS'] },
      { label: '订单面积', valueArr: [''], unitArr: ['m2'] },
      { label: 'IPC标准', valueArr: [''], unitArr: [''] },
      { label: '打叉板标准', valueArr: [''], unitArr: [''] },
      { label: '打叉数量', valueArr: [''], unitArr: [''] },
      { label: '环保要求', valueArr: [''], unitArr: [''] },
      { label: '包装要求', valueArr: [''], unitArr: [''] },
      { label: '板翘曲(max)', valueArr: ['0.5%'], unitArr: [''] },
      { label: '可返工修补', valueArr: [''], unitArr: [''] },
      { label: '离子污染', valueArr: [''], unitArr: ['ug/m2'] },
      { label: '二维码要求', valueArr: ['???'], unitArr: [''] },
      { label: '难度等级', valueArr: [''], unitArr: [''] },
    ],
    m1: [
      { label: '板层数(层)', valueArr: ['4'], unitArr: [''] },
      { label: 'PCS尺寸', valueArr: ['41.5989', '*', '40.6049'], unitArr: ['mm'] },
      { label: 'SET尺寸', valueArr: ['142.797', '*', '142.795'], unitArr: ['mm'] },
      { label: '拼版方式', valueArr: ['3', '*', '3'], unitArr: [] },
      { label: '拼板数(PCS/SET)', valueArr: ['9'], unitArr: [] },
      { label: '交货单位', valueArr: [''], unitArr: [''] },
      { label: '拼板来源', valueArr: [''], unitArr: [''] },
      { label: '盲埋孔', valueArr: ['否'], unitArr: [''] },
      { label: 'PWB板类型', valueArr: ['硬板'], unitArr: [''] },
      { label: '成品板厚', valueArr: ['1.6'], unitArr: ['mm'] },
      { label: '板厚公差', valueArr: ['±0.16MM'], unitArr: [''] },
      { label: '外层基铜', valueArr: [''], unitArr: ['oz'] },
      { label: '外层成品铜', valueArr: ['???'], unitArr: ['oz'] },
      { label: '外层序列', valueArr: ['???/???'], unitArr: [''] },
      { label: '最小线宽', valueArr: ['14'], unitArr: ['mil'] },
      { label: '最小线距', valueArr: ['9.84'], unitArr: ['mil'] },
      { label: '通孔-孔铜厚(min)', valueArr: ['???'], unitArr: ['um'] },
      { label: '孔铜(avg)', valueArr: [''], unitArr: ['um'] },
      { label: '残铜率', valueArr: ['37.18/65.10/65.31/35.38'], unitArr: [''] },
      { label: '阻抗控制', valueArr: ['是'], unitArr: [''] },
      { label: '阻抗公差(±)', valueArr: [''], unitArr: [''] },
      { label: '阻抗组数', valueArr: [''], unitArr: [''] },
      { label: '文件格式', valueArr: [''], unitArr: [''] },
    ],
    m2: [
      { label: '板材类型', valueArr: ['FR4'], unitArr: [''] },
      { label: '板材品牌', valueArr: [''], unitArr: [''] },
      { label: '板材型号', valueArr: [''], unitArr: [''] },
      { label: 'TG(min)', valueArr: ['???'], unitArr: ['°C'] },
      { label: '卤素要求', valueArr: [''], unitArr: [''] },
      { label: 'CTI值(min)', valueArr: ['???'], unitArr: ['V'] },
      { label: '耐CAF', valueArr: [''], unitArr: [''] },
      { label: '导热系数', valueArr: [''], unitArr: ['W/(m·K)'] },
    ],
    m3: [
      { label: '板材利用率', valueArr: [''], unitArr: ['%'] },
      { label: 'Sheet尺寸', valueArr: ['', '*', ''], unitArr: ['mm'] },
      { label: 'PCS/Sheet', valueArr: [''], unitArr: [''] },
      { label: 'SET/Sheet', valueArr: [''], unitArr: [''] },
      { label: 'A-PNL/sheet', valueArr: [''], unitArr: [''] },
      { label: 'B-PNL/sheet', valueArr: [''], unitArr: [''] },
      { label: 'PNLA尺寸', valueArr: ['', '*', ''], unitArr: ['mm'] },
      { label: 'PCS/PNLA', valueArr: [''], unitArr: [''] },
      { label: 'SET/PNLA', valueArr: [''], unitArr: [''] },
      { label: 'PNLB尺寸', valueArr: ['', '*', ''], unitArr: ['mm'] },
      { label: 'PCS/PNLB', valueArr: [''], unitArr: [''] },
      { label: 'SET/PNLB', valueArr: [''], unitArr: [''] },
      { label: '余料宽度(纬/经)', valueArr: ['', '*', ''], unitArr: ['mm'] },
    ],
    m4: [
      { label: '压合次数', valueArr: [''], unitArr: ['次'] },
      { label: '内层基铜', valueArr: [''], unitArr: ['oz'] },
      { label: '内层成品铜厚', valueArr: ['???'], unitArr: ['oz'] },
      { label: '内层序列', valueArr: ['???/???'], unitArr: [''] },
    ],
    m5: [
      { label: '通孔最小孔', valueArr: ['0.299999'], unitArr: ['mm'] },
      { label: '通孔孔数', valueArr: ['45'], unitArr: ['个', '/PCS'] },
      { label: '最小槽孔', valueArr: [''], unitArr: ['mm'] },
      { label: '机械槽孔数', valueArr: ['0'], unitArr: ['条'] },
      { label: '槽孔折算圆孔', valueArr: ['0'], unitArr: ['个'] },
      { label: '通孔密度', valueArr: ['2.664'], unitArr: ['万/m2', '/PCS'] },
      { label: '机械盲埋孔数', valueArr: ['0'], unitArr: ['个'] },
      { label: '机械盲埋孔径', valueArr: [''], unitArr: ['mm'] },
      { label: '机械盲埋孔密度', valueArr: ['0'], unitArr: ['万/m2', '/PCS'] },
      { label: '总孔数', valueArr: ['45'], unitArr: ['个'] },
      { label: '总钻孔密度', valueArr: ['2.664'], unitArr: ['万/m2', '/PCS'] },
      { label: '钻孔结构', valueArr: ['-'], unitArr: [] },
      { label: '盘中孔', valueArr: [''], unitArr: ['个'] },
      { label: '重孔', valueArr: ['0'], unitArr: ['个'] },
      { label: '叠孔数', valueArr: ['0'], unitArr: ['个'] },
      { label: '同层孔距', valueArr: ['11.499'], unitArr: ['mil'] },
      { label: '层间孔距', valueArr: [''], unitArr: ['mil'] },
    ],
    m6: [
      { label: '激光最小孔', valueArr: [''], unitArr: ['mm'] },
      { label: '激光孔数', valueArr: ['0'], unitArr: ['个'] },
      { label: '激光孔密度', valueArr: ['0'], unitArr: ['万/m2', '/PCS'] },
      { label: '激光阶数', valueArr: [''], unitArr: ['阶'] },
      { label: '激光次数', valueArr: [''], unitArr: ['次'] },
    ],
    m7: [
      { label: '压接孔', valueArr: [''], unitArr: [''] },
      { label: '压接孔数', valueArr: [''], unitArr: ['个'] },
      { label: '沉头', valueArr: ['否'], unitArr: [''] },
      { label: '沉头孔数', valueArr: ['0'], unitArr: ['个'] },
      { label: '控深加工', valueArr: [''], unitArr: [''] },
      { label: '背钻', valueArr: ['否'], unitArr: [''] },
      { label: '背钻孔数', valueArr: ['0'], unitArr: ['个'] },
      { label: '背钻信息', valueArr: [''], unitArr: [''] },
      { label: '半孔工艺', valueArr: [''], unitArr: [''] },
      { label: '半孔边数', valueArr: [''], unitArr: [''] },
      { label: '半孔数量', valueArr: ['24'], unitArr: ['个'] },
      { label: '半孔直径(min)', valueArr: [''], unitArr: ['mm'] },
      { label: '半孔到孔间距', valueArr: [''], unitArr: ['mm'] },
    ],
    m8: [
      { label: '阻焊颜色', valueArr: ['绿色'], unitArr: [''] },
      { label: '阻焊光泽', valueArr: [''], unitArr: [''] },
      { label: '阻焊品牌', valueArr: [''], unitArr: [''] },
      { label: '过孔处理', valueArr: ['油墨塞孔'], unitArr: [''] },
      { label: '塞孔工艺', valueArr: ['???'], unitArr: [''] },
      { label: '塞孔次数', valueArr: [''], unitArr: [''] },
      { label: '填孔电镀次数', valueArr: [''], unitArr: [''] },
      { label: '顶层阻焊', valueArr: ['绿色'], unitArr: [''] },
      { label: '底层阻焊', valueArr: ['绿色'], unitArr: [''] },
      { label: '油墨型号', valueArr: [''], unitArr: [''] },
    ],
    m9: [
      { label: '字符颜色', valueArr: ['白色'], unitArr: [''] },
      { label: '字符品牌', valueArr: [''], unitArr: [''] },
      { label: '字符型号', valueArr: [''], unitArr: [''] },
      { label: '顶层颜色', valueArr: ['白色'], unitArr: [''] },
      { label: '底层颜色', valueArr: ['白色'], unitArr: [''] },
    ],
    m10: [
      { label: '表面处理', valueArr: ['???'], unitArr: [''] },
      { label: '化金厚度(min)', valueArr: ['1'], unitArr: ['uinch'] },
      { label: '镍厚度', valueArr: ['118.1102362205'], unitArr: ['uinch'] },
      { label: '钯厚度', valueArr: [''], unitArr: [''] },
      { label: '锡厚度', valueArr: [''], unitArr: [''] },
      { label: '顶层露铜面积', valueArr: ['9.9', '%', '132.7'], unitArr: ['mm2'] },
      { label: '底层露铜面积', valueArr: ['8.68', '%', '116.09'], unitArr: ['mm2'] },
      { label: '总露铜面积', valueArr: ['18.59', '%', '248.79'], unitArr: ['mm2'] },
    ],
    m11: [
      { label: '电镀硬金(金手指)', valueArr: ['否'], unitArr: [''] },
      { label: '电硬金厚度(min)', valueArr: [''], unitArr: ['uinch'] },
      { label: '镀镍厚', valueArr: [''], unitArr: ['uinch'] },
      { label: '计数单位', valueArr: [''], unitArr: ['u"'] },
      { label: 'TOP面/BOT面支数', valueArr: ['', '+', ''], unitArr: ['支'] },
      { label: '总支数', valueArr: [''], unitArr: ['支'] },
      { label: 'TOP面手指尺寸', valueArr: ['', '*', ''], unitArr: ['mm'] },
      { label: 'BOT面手指尺寸', valueArr: ['', '*', ''], unitArr: ['mm'] },
      { label: '最大手指长/宽', valueArr: ['', '*', ''], unitArr: ['支'] },
      { label: 'TOP面手指面积', valueArr: ['', '%', ''], unitArr: ['cm2'] },
      { label: 'BOT面手指面积', valueArr: ['', '%', ''], unitArr: ['cm2'] },
      { label: '总计(sum)', valueArr: ['', '%', ''], unitArr: ['cm2'] },
    ],
    m12: [
      { label: '成型方式', valueArr: ['???'], unitArr: [''] },
      { label: '锣程长度', valueArr: ['0.348'], unitArr: ['m', '/PCS'] },
      { label: 'V-CUT(横向)', valueArr: [''], unitArr: ['刀', '/SET'] },
      { label: 'V-CUT(竖向)', valueArr: [''], unitArr: ['刀', '/SET'] },
      { label: '跳刀V-CUT', valueArr: [''], unitArr: ['刀', '/PCS'] },
      { label: 'V-CUT总刀数', valueArr: [''], unitArr: ['刀', '/SET'] },
      { label: 'V-CUT长度', valueArr: [''], unitArr: ['m', '/SET'] },
      { label: 'V-程', valueArr: [''], unitArr: ['m', '/m2'] },
      { label: '斜边', valueArr: ['NO'], unitArr: [''] },
    ],
    m13: [
      { label: '电测要求', valueArr: [''], unitArr: [''] },
      { label: '最小测试点', valueArr: [''], unitArr: ['mil'] },
      { label: '测试点数', valueArr: ['45'], unitArr: ['个', '/PCS'] },
    ],
    m14: [
      { label: '碳油', valueArr: [''], unitArr: [''] },
      { label: '蓝胶', valueArr: [''], unitArr: [''] },
      { label: '金属包边', valueArr: [''], unitArr: [''] },
      { label: '导电胶', valueArr: [''], unitArr: [''] },
      { label: '埋铜块', valueArr: [''], unitArr: [''] },
      { label: '埋电容', valueArr: [''], unitArr: [''] },
      { label: '埋电感', valueArr: [''], unitArr: [''] },
      { label: '埋电阻', valueArr: [''], unitArr: [''] },
    ],
    m15: [
      { label: '内层最小线宽', valueArr: ['20'], unitArr: ['mil'] },
      { label: '内层最小线距', valueArr: ['15'], unitArr: ['mil'] },
      { label: '各内层最小线宽', valueArr: ['999/999'], unitArr: ['mil'] },
      { label: '各内层最小线距', valueArr: ['999/999'], unitArr: ['mil'] },
      { label: '内层孔到线', valueArr: ['14.8235'], unitArr: ['mil'] },
      { label: '内层最小孔环', valueArr: ['11.9394'], unitArr: ['mil'] },
      { label: '内层最小PAD', valueArr: ['27.559'], unitArr: ['mil'] },
      { label: '内层PAD到PAD', valueArr: [''], unitArr: ['mil'] },
      { label: '内层PAD到线', valueArr: [''], unitArr: ['mil'] },
      { label: '内层孔距PAD', valueArr: [''], unitArr: ['mil'] },
      { label: '内层孔距铜', valueArr: ['9.87388'], unitArr: ['mil'] },
      { label: '内层PAD到板边', valueArr: [''], unitArr: ['mil'] },
      { label: '内层线到板边', valueArr: [''], unitArr: ['mil'] },
      { label: '内层隔离带宽', valueArr: [''], unitArr: ['mil'] },
    ],
    m16: [
      { label: '外层最小线宽', valueArr: ['14'], unitArr: ['mil'] },
      { label: '外层最小线距', valueArr: ['9.84'], unitArr: ['mil'] },
      { label: '各外层最小线宽', valueArr: ['14/14'], unitArr: ['mil'] },
      { label: '各外层最小线距', valueArr: ['9.84/999'], unitArr: ['mil'] },
      { label: '外层PAD距铜', valueArr: [''], unitArr: ['mil'] },
      { label: '外层最小孔环', valueArr: ['9.97536'], unitArr: ['mil'] },
      { label: '外层最小PAD', valueArr: ['23.68'], unitArr: ['mil'] },
      { label: '外层PAD到PAD', valueArr: ['14.6586'], unitArr: ['mil'] },
      { label: '外层PAD到线', valueArr: ['4.80241'], unitArr: ['mil'] },
      { label: '外层孔距线', valueArr: [''], unitArr: ['mil'] },
      { label: '外层孔距PAD', valueArr: [''], unitArr: ['mil'] },
      { label: '外层孔距铜', valueArr: [''], unitArr: ['mil'] },
      { label: '外层PAD到板边', valueArr: ['10.3415'], unitArr: ['mil'] },
      { label: '外层线到板边', valueArr: ['6.01627'], unitArr: ['mil'] },
      { label: '孔距板边', valueArr: [''], unitArr: ['mil'] },
      { label: 'BGA个数', valueArr: ['0'], unitArr: ['组', '/PCS'] },
      { label: 'BGA尺寸', valueArr: [''], unitArr: ['mil'] },
      { label: 'BGA节距', valueArr: [''], unitArr: ['mil'] },
      { label: 'IC尺寸', valueArr: ['47.31'], unitArr: ['mil'] },
      { label: '备注信息', valueArr: [''], unitArr: [''] },
    ],
    m17: [
      { label: 'test', valueArr: ['11'], unitArr: [''] },
      { label: 'test1', valueArr: ['2'], unitArr: [''] },
      { label: 'test2', valueArr: ['3'], unitArr: [''] },
      { label: 'test3', valueArr: ['4'], unitArr: [''] },
    ],
  },
}
